version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/company_dating
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DRIVER=org.postgresql.Driver
      - JPA_DDL_AUTO=update
      - JPA_SHOW_SQL=true
      - JPA_FORMAT_SQL=true
      - JPA_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - JWT_SECRET=dGhpc2lzYXZlcnlsb25nc2VjcmV0a2V5Zm9yanNvbndlYnRva2Vuc2lnbmluZ3RoYXRpc2F0bGVhc3QyNTZiaXRz
      - JWT_EXPIRATION=86400000
      - MAX_FILE_SIZE=10MB
      - MAX_REQUEST_SIZE=10MB
      - MAIL_HOST=smtp.example.com
      - MAIL_PORT=587
      - MAIL_USERNAME=your_email@example.com
      - MAIL_PASSWORD=your_email_password
      - MAIL_SMTP_AUTH=true
      - MAIL_SMTP_STARTTLS=true
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=company_dating
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 